
name: runner info

# This workflow is triggered on pushes to the repository. 666

on:   push

jobs:

  job1: 

    runs-on: self-hosted

  

    steps:

    - name: Dump runner context

      env:

        RUNNER_CONTEXT: ${{ toJson(runner) }}

      run: ${env:RUNNER_CONTEXT}
